import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';import {createRequire} from 'node:module';import React,{act} from 'react';import {createRoot} from 'react-dom/client';import {JSDOM} from 'jsdom';
const require=createRequire(import.meta.url);
const dom=new JSDOM('<!doctype html><html><head></head><body><div id="root"></div></body></html>',{url:'http://localhost'});
globalThis.window=dom.window;globalThis.document=dom.window.document;globalThis.HTMLElement=dom.window.HTMLElement;globalThis.IS_REACT_ACT_ENVIRONMENT=true;
let client;window.__ModuleLoader__={load({id,factory}){assert.equal(id,'dsh-desktop-workflow');client=factory(require);}};
vm.runInThisContext(await readFile(new URL('../lib/client.js',import.meta.url),'utf8'));
const waiting={mode:'waiting',title:'Waiting',status:'pending',stage:'waiting',stages:[],jev:null,sourceNotice:'No file configured'};
function makeHost(call){const cleanups=[];let definition,Body;return {cleanups,get Body(){return Body;},get definition(){return definition;},effect(fn){cleanups.push(fn());},connection:{rpc:{call}},sidebarRightTabs:{register(d){definition=d;return()=>{definition=null;};}},slots:{inject(name,fn){assert.equal(name,'sidebar.right.pane.tab');return fn();},register(d,C){assert.equal(d.key,'dsh-desktop-workflow');Body=C;return()=>{Body=null;};}}};}
const click=async button=>act(async()=>button.dispatchEvent(new window.MouseEvent('click',{bubbles:true})));
test('host factory registers native tab, renders states, selection, keyboard and cleanup',async()=>{let requests=0;const host=makeHost(async()=>{requests++;return {ok:true,value:waiting};});client.apply(host);assert.equal(host.definition.kind,'dsh-desktop-workflow');assert.equal(document.querySelectorAll('style[data-dsh-desktop-workflow]').length,1);const root=createRoot(document.getElementById('root'));await act(async()=>root.render(React.createElement(host.Body)));assert.equal(requests,1);assert.match(document.body.textContent,/等待工作流/);await click([...document.querySelectorAll('button')].find(b=>b.textContent.includes('查看演示')));assert.match(document.body.textContent,/模拟工作流/);const nodes=[...document.querySelectorAll('.wf-node')];assert.equal(nodes.length,6);await click(nodes[0]);assert.match(document.querySelector('.wf-inspector').textContent,/路由决策/);await act(async()=>nodes[0].dispatchEvent(new window.KeyboardEvent('keydown',{key:'End',bubbles:true})));assert.equal(nodes[5].getAttribute('aria-pressed'),'true');assert.equal(document.activeElement,nodes[5]);const timeline=document.querySelector('.wf-activity-toggle');const expanded=timeline.getAttribute('aria-expanded');await click(timeline);assert.notEqual(timeline.getAttribute('aria-expanded'),expanded);await click(document.querySelector('.wf-refresh-button'));assert.equal(requests,2);assert.ok(!document.body.textContent.includes('模拟工作流'));await act(async()=>root.unmount());for(const fn of host.cleanups.reverse())await fn();assert.equal(document.querySelectorAll('style[data-dsh-desktop-workflow]').length,0);assert.equal(host.definition,null);});
test('leaving demo into a bridge failure never retains synthetic results',async()=>{let fail=false;const host=makeHost(async()=>fail?{ok:false,error:{message:'State unavailable'}}:{ok:true,value:waiting});client.apply(host);const root=createRoot(document.getElementById('root'));await act(async()=>root.render(React.createElement(host.Body)));await click([...document.querySelectorAll('button')].find(b=>b.textContent.includes('查看演示')));fail=true;await click(document.querySelector('.wf-refresh-button'));assert.match(document.body.textContent,/State unavailable/);assert.ok(!document.body.textContent.includes('模拟工作流'));assert.ok(!document.body.textContent.includes('模拟 ·'));await act(async()=>root.unmount());for(const fn of host.cleanups.reverse())await fn();});
test('unmount aborts pending RPC',async()=>{let signal;const host=makeHost((_c,_e,_p,s)=>{signal=s;return new Promise(()=>{});});client.apply(host);const root=createRoot(document.getElementById('root'));await act(async()=>root.render(React.createElement(host.Body)));await act(async()=>root.unmount());assert.equal(signal.aborted,true);for(const fn of host.cleanups.reverse())await fn();});
test('newer demo navigation wins over a late live response',async()=>{let resolve;const host=makeHost(()=>new Promise(r=>{resolve=r;}));client.apply(host);const root=createRoot(document.getElementById('root'));await act(async()=>root.render(React.createElement(host.Body)));await click([...document.querySelectorAll('button')].find(b=>b.textContent.includes('查看演示')));await act(async()=>resolve({ok:true,value:waiting}));assert.match(document.body.textContent,/模拟工作流/);await act(async()=>root.unmount());for(const fn of host.cleanups.reverse())await fn();});
test('producer text is never rendered as HTML',async()=>{const attack='<img src=x onerror=alert(1)><script>alert(1)</script>';const snapshot={...waiting,mode:'live',title:attack,status:'running',stage:'work',jev:{model:attack,effectiveRoute:attack},stages:[{stage:'work',status:'running',summary:attack,evidence:[attack]}]};const host=makeHost(async()=>({ok:true,value:snapshot}));client.apply(host);const root=createRoot(document.getElementById('root'));await act(async()=>root.render(React.createElement(host.Body)));assert.equal(document.querySelectorAll('img,script').length,0);assert.ok(document.body.textContent.includes(attack));await act(async()=>root.unmount());for(const fn of host.cleanups.reverse())await fn();});
test('request deadline recovers from an unresponsive bridge without cancelling future reads',async()=>{const lifecycle=new AbortController();let requestSignal;await assert.rejects(client.requestWithDeadline(signal=>{requestSignal=signal;return new Promise(()=>{});},lifecycle.signal,5),/未响应/);assert.equal(requestSignal.aborted,true);assert.equal(lifecycle.signal.aborted,false);assert.equal(await client.requestWithDeadline(async()=>42,lifecycle.signal,5),42);});
test('inspect and failed-routing source semantics survive the rendered host factory',async()=>{let snapshot={...waiting,mode:'live',title:'Read-only investigation',runId:'run-inspect',executionMode:'inspect',status:'running',stage:'work',routingStatus:'completed',jev:{model:'reported',effectiveRoute:'execute'},stages:[{stage:'work',status:'running',summary:'Read source',evidence:[]}]};const host=makeHost(async()=>({ok:true,value:snapshot}));client.apply(host);const root=createRoot(document.getElementById('root'));await act(async()=>root.render(React.createElement(host.Body)));assert.match(document.querySelectorAll('.wf-node')[2].textContent,/检查/);assert.match(document.body.textContent,/run-inspect/);snapshot={...snapshot,runId:'run-routing-failed',stage:'jev-routing',routingStatus:'failed',status:'blocked',jev:null,stages:[]};await click(document.querySelector('.wf-refresh-button'));assert.ok(document.querySelectorAll('.wf-node')[0].classList.contains('wf-node--failed'));assert.match(document.querySelector('.wf-inspector').textContent,/失败/);await act(async()=>root.unmount());for(const fn of host.cleanups.reverse())await fn();});
