import {test} from 'node:test';import assert from 'node:assert/strict';
import {createJevClient,parseJevResponse,classifyDecision,stepDecision,JEV_ENDPOINT} from '../src/jev-client.js';
import {JevTeamController} from '../src/jev-controller.js';
import {createTeamRuntime} from '../src/team-runtime.js';
import {fixtureDependencies,settings,teamHost} from './helpers/team-host.mjs';
const choices=['small','medium','high','escalate','other'];
const answer=(choice,keys=choices)=>({type:'choice',choice,confidence:.9,probabilities:Object.fromEntries(keys.map(k=>[k,k===choice?1:0]))});
const classify=()=>({answers:{lane:answer('small'),security_sensitive:{type:'noul',noul:0},underspecified:{type:'noul',noul:0}}});
const next=(choice='complete',confidence=.9)=>({implemented:{noul:1},in_scope:{noul:1},next:{choice,confidence}});
const facts={checksPassed:true,checksFailed:0,checksRun:true,scopeOk:true,diffAvailable:true,protectedOk:true,verified:true,diffEmpty:false,expectsChanges:true,reason:'fixture facts',checks:[]};
const config=()=>({sessionId:'fixture-session',goal:'Change fixture source',...settings(),limits:{...settings().limits,maxAgents:32,maxRounds:4,maxRetries:1}});
function controller({actions=['complete'],evidence=facts,lane='small',execute,decide}={}){const deps=fixtureDependencies(),calls=[];let step=0;deps.jev.decide=decide|| (async ({phase})=>phase==='classify'?{lane:{choice:lane,confidence:.9},security_sensitive:{noul:0},underspecified:{noul:0}}:next(actions[Math.min(step++,actions.length-1)]));deps.verifier.collect=async s=>s.phase==='baseline'?{verified:true,reason:'fixture baseline'}:s.phase==='seal'?{verified:true,sealed:true,reason:'fixture seal'}:{...evidence,runId:s.runId,round:s.round};const plan={summary:'Fixture plan',tasks:[{id:'write',title:'Fixture edit',role:'worker',instructions:'Fixture only',dependsOn:[]}]};const exec=async s=>{calls.push(s);return execute?execute(s):{stopReason:'completed',structured:s.role==='reviewer'?{verdict:'approve',summary:'Fixture review',issues:[]}:plan,output:'fixture'};};return {controller:new JevTeamController({...deps,execute:exec}),calls};}
async function run(f,input=config()){const start=f.controller.start(input);try{return await f.controller.wait(start.id);}finally{await f.controller.dispose();}}
test('production missing key blocks preflight without model calls, never demo or regular router fallback',async()=>{const h=teamHost(),r=createTeamRuntime(h.ctx);try{const c=r.snapshot('fixture-session');await assert.rejects(r.start({sessionId:'fixture-session',contextKey:c.context.contextKey,requestId:'no-key-request',goal:'fixture',settings:settings()}),/凭据/);assert.equal(h.calls.length,0);assert.equal((await r.catalog()).jev.available,false);}finally{await r.dispose();}});
test('TypeSafe credential only in fixed Authorization transport, bounded state, no redirect or fallback',async()=>{let captured;const c=createJevClient({credentialEnv:'FIXTURE_KEY'},{resolveCredential:()=> 'fixture-never-real-key',fetchImpl:async(url,init)=>{captured={url,init};return Response.json(classify());}});const a=await c.decide({phase:'classify',goal:'Read a@example.com '+ 'x'.repeat(4000),signal:new AbortController().signal});assert.equal(classifyDecision(a).lane,'small');assert.equal(captured.url,JEV_ENDPOINT);assert.equal(captured.init.redirect,'error');assert.match(captured.init.headers.Authorization,/fixture-never-real-key/);assert.ok(!captured.init.body.includes('fixture-never-real-key'));const body=JSON.parse(captured.init.body);assert.ok(body.state.task.length<=3000);assert.ok(!body.state.task.includes('a@example.com'));assert.ok(!JSON.stringify(c.status()).includes('fixture-never-real-key'));await assert.rejects(c.decide({phase:'classify',goal:'password=secret-value',signal:new AbortController().signal}),/凭据/);});
test('Jev rejects malformed distributions, wrong noul types, unavailable service and cancellation',async()=>{const bad=classify();bad.answers.lane.probabilities.rogue=1;assert.throws(()=>parseJevResponse(bad,'classify'));const wrong=classify();wrong.answers.security_sensitive.noul='1';assert.throws(()=>parseJevResponse(wrong,'classify'));const c=createJevClient({credentialEnv:'FIXTURE_KEY'},{resolveCredential:()=> 'fixture',fetchImpl:async()=>{throw Error('private raw secret diagnostic');}});await assert.rejects(c.decide({phase:'classify',goal:'fixture',signal:new AbortController().signal}),e=>!e.message.includes('private raw'));const abort=new AbortController();abort.abort();await assert.rejects(c.decide({phase:'classify',goal:'fixture',signal:abort.signal}),/取消/);});
test('Jev can complete only after independent checks and exact pinned six role models',async()=>{const f=controller();const result=await run(f);assert.equal(result.status,'completed');assert.equal(result.jev.mode,'fixture');assert.equal(result.jev.decisions.length,2);assert.ok(result.nodes.some(n=>n.kind==='verification'));for(const call of f.calls)assert.deepEqual(call.model,config().roles[call.role]);});
test('worker and reviewer claims cannot override failed or absent independent evidence',async()=>{for(const evidence of [{...facts,checksPassed:false,checksFailed:1},{...facts,protectedOk:false},{...facts,diffAvailable:false},{...facts,verified:false}]){const result=await run(controller({evidence}));assert.notEqual(result.status,'completed');}});
test('verify repeats trusted checks without redispatching implementation',async()=>{const f=controller({actions:['other','complete']});const result=await run(f);assert.equal(result.status,'completed');assert.equal(f.calls.filter(s=>s.role==='worker').length,1);assert.equal(result.jev.round,2);});
test('escalation is one lane per decision, preserves models and top lane blocks for person',async()=>{const f=controller({actions:['needs_stronger_model']});const result=await run(f);assert.equal(result.status,'blocked');assert.equal(result.jev.lane,'escalate');assert.deepEqual(result.events.filter(e=>e.type==='lane_escalated').map(e=>e.message.split(' → ')[1].split(';')[0]),['medium','high','escalate']);for(const call of f.calls)assert.deepEqual(call.model,config().roles[call.role]);});
test('needs_person and Jev outage do not dispatch another cycle',async()=>{const f=controller({actions:['needs_person']});assert.equal((await run(f)).status,'blocked');assert.equal(f.calls.filter(s=>s.role==='worker').length,1);const bad=controller({decide:async()=>{throw new Error('fixture outage');}});assert.notEqual((await run(bad)).status,'completed');assert.equal(bad.calls.length,0);});
test('loop pre-rules enforce failing checks repeated-attempt escalation and completion thresholds',()=>{assert.equal(stepDecision(next(),{...facts,checksFailed:1},{lane:'small',attempts:1}).action,'retry');assert.equal(stepDecision(next(),{...facts,checksFailed:1},{lane:'small',attempts:2}).action,'escalate');assert.equal(stepDecision(next('complete',.59),facts,{lane:'medium',attempts:1}).action,'verify');});
test('all bounded rounds and Jev call caps stop without a false completion',async()=>{const f=controller({actions:['other']});assert.equal((await run(f)).status,'blocked');const g=controller();const c=config();c.limits.maxJevCalls=1;const result=await run(g,c);assert.notEqual(result.status,'completed');assert.equal(result.jev.decisions.length,1);});
test('continue and retry make bounded new cycles; no local worker retry bypasses Jev',async()=>{for(const action of ['continue','retry_differently']){let steps=0;const f=controller({decide:async({phase})=>phase==='classify'?{lane:{choice:'small',confidence:.9},security_sensitive:{noul:0},underspecified:{noul:0}}:++steps===1?{implemented:{noul:.2},in_scope:{noul:1},next:{choice:action,confidence:.9}}:next()});const result=await run(f);assert.equal(result.status,'completed');assert.equal(f.calls.filter(c=>c.role==='worker').length,2);assert.equal(result.jev.decisions[1].action,action==='continue'?'continue':'retry');}});
test('cancellation during independent Jev waits for settle and never begins a role model',async()=>{let entered=false,release;const f=controller({decide:async({signal})=>{entered=true;await new Promise(resolve=>{release=resolve;signal.addEventListener('abort',resolve,{once:true});});throw Error('fixture cancelled');}});const s=f.controller.start(config());while(!entered)await new Promise(r=>setImmediate(r));f.controller.cancel(s.sessionId,s.id);release?.();const result=await f.controller.wait(s.id);assert.equal(result.status,'cancelled');assert.equal(f.calls.length,0);await f.controller.dispose();});
test('step uses upstream typed questions and only bounded evidence projection',async()=>{let request;const keys=['complete','continue','retry_differently','needs_stronger_model','needs_person','other'];const c=createJevClient({credentialEnv:'FIXTURE_KEY'},{resolveCredential:()=> 'fixture',fetchImpl:async(_url,init)=>{request=JSON.parse(init.body);return Response.json({answers:{implemented:{type:'noul',noul:1},in_scope:{type:'noul',noul:1},next:answer('complete',keys)}});}});await c.decide({phase:'step',goal:'fixture',evidence:{diffStat:'x'.repeat(2000),checkSummary:'y'.repeat(3000),privateSource:'MUST_NOT_SEND',checks:[{private:'MUST_NOT_SEND'}]},notes:'z'.repeat(2000),signal:new AbortController().signal});assert.deepEqual(Object.keys(request.questions),['implemented','in_scope','next']);assert.equal(request.state.diff_stat.length,1500);assert.equal(request.state.checks.length,2500);assert.equal(request.state.notes.length,1200);assert.ok(!JSON.stringify(request).includes('MUST_NOT_SEND'));});
