import {test} from 'node:test';
import assert from 'node:assert/strict';
import {validateProduction,validateConfig,selectRoleModel,configuredModels,TEAM_ROLES} from '../src/team-contracts.js';
import {JevTeamController} from '../src/jev-controller.js';
import {settings,fixtureDependencies} from './helpers/team-host.mjs';
const selection=model=>({provider:'fixture',model,maxTokens:4096});
test('production defaults never turn the 10m experiment into a permanent token budget',()=>{const p=validateProduction();assert.deepEqual(p.budget,{enabled:false,tokenLimit:0});assert.equal(p.routing.enabled,false);assert.equal(p.jev.model,'jev-latest');assert.equal(p.jev.shadow.enabled,false);assert.equal(p.jev.shadow.model,'');assert.deepEqual(validateProduction({budget:{enabled:true,tokenLimit:25_000_000}}).budget,{enabled:true,tokenLimit:25_000_000});for(const tokenLimit of [0,-1,1.1,1e9+1,NaN])assert.throws(()=>validateProduction({budget:{enabled:true,tokenLimit}}));});
test('model candidate schema rejects unknown fields and credentials, and preserves explicit candidates only',()=>{for(const routing of [{enabled:true,roles:{unknown:{weak:selection('x')}}},{enabled:true,roles:{worker:{cheap:selection('x')}}},{enabled:true,roles:{worker:{weak:{...selection('x'),apiKey:'never'}}}}])assert.throws(()=>validateProduction({routing}));const config=validateConfig({...settings(),sessionId:'test',goal:'test',routing:{enabled:true,roles:{worker:{weak:selection('weak'),strong:selection('strong')}}}});assert.equal(selectRoleModel(config,'worker','small').model.model,'weak');assert.equal(selectRoleModel(config,'worker','medium').model.model,'model');assert.equal(selectRoleModel(config,'worker','high').model.model,'strong');assert.equal(selectRoleModel(config,'worker','escalate').model.model,'strong');assert.equal(selectRoleModel(config,'reviewer','small').model.model,'model');assert.equal(Object.keys(configuredModels(config)).length,8);assert.equal(config.roles.worker.model,'model');});
test('primary Jev versions and explicit shadow pinning are validated before dispatch',()=>{for(const model of ['jev-latest','jev-preview','jev-1.2.3','jev-1.2.3-rc.1'])assert.equal(validateProduction({jev:{model}}).jev.model,model);for(const model of ['jev-secret','jev-latest','', 'jev-1.2.3/'])assert.throws(()=>validateProduction({jev:{shadow:{enabled:true,model,maxCalls:2}}}));assert.throws(()=>validateProduction({jev:{shadow:{enabled:true,model:'jev-1.2.3',maxCalls:21}}}));assert.equal(validateProduction({jev:{shadow:{enabled:true,model:'jev-1.2.3-rc.1',maxCalls:0}}}).jev.shadow.maxCalls,0);});
test('configured role routing reaches actual execute specs and never mutates six base roles',async()=>{const deps=fixtureDependencies(),seen=[];const c=new JevTeamController({...deps,trace:true,execute:async s=>{seen.push(s);return {stopReason:'completed',structured:s.role==='reviewer'?{verdict:'approve',summary:'Review fixture',issues:[]}:{summary:'Fixture plan',tasks:[{id:'work',title:'Work',instructions:'Fixture work',role:'worker',dependsOn:[]}]}};}});const input={...settings(),sessionId:'routing-fixture',goal:'Test explicit routing',routing:{enabled:true,roles:Object.fromEntries(TEAM_ROLES.map(role=>[role,{weak:selection('weak')}]))}};try{const run=c.start(input),result=await c.wait(run.id);assert.equal(result.status,'completed');assert.ok(seen.length);assert.ok(seen.every(s=>s.model.model==='weak'));assert.ok(TEAM_ROLES.every(r=>result.roles[r].model==='model'));assert.ok(result.production.routing.decisions.every(r=>r.tier==='weak'));assert.ok(c.trace(input.sessionId).events.some(e=>e.type==='routing'));}finally{await c.dispose();}});

test('untrusted Jev response model cannot bypass the metadata whitelist into public snapshots',async()=>{
 const {parseJevResponse}=await import('../src/jev-client.js');const {readFileSync}=await import('node:fs');
 const canary='sk-SYNTHETIC-DO-NOT-USE-123456789';const deps=fixtureDependencies();
 deps.jev.decide=async({phase})=>{const policy=JSON.parse(readFileSync(new URL(`../src/vendor/${phase==='classify'?'lane':'loop-step'}.json`,import.meta.url),'utf8'));const answers={};for(const[name,q]of Object.entries(policy.questions)){if(q.type==='choice'){const choice=name==='lane'?'small':'complete';answers[name]={type:'choice',choice,confidence:1,probabilities:Object.fromEntries(Object.keys(q.criteria).map(key=>[key,key===choice?1:0]))};}else answers[name]={type:'noul',noul:['security_sensitive','underspecified'].includes(name)?0:1};}return parseJevResponse({model:canary,answers},phase,{requestedModel:'jev-latest'});};
 const c=new JevTeamController({...deps,perRunJev:true,execute:async s=>({stopReason:'completed',structured:s.role==='reviewer'?{verdict:'approve',summary:'Review fixture',issues:[]}:{summary:'Plan fixture',tasks:[{id:'work',title:'Work',instructions:'Fixture work',role:'explorer',dependsOn:[]}]}})});
 try{const run=c.start({...settings(),sessionId:'redacted-status',goal:'Test metadata projection'});const result=await c.wait(run.id);assert.equal(result.status,'completed');assert.ok(!JSON.stringify(result).includes(canary));assert.ok(!JSON.stringify(c.snapshot('redacted-status')).includes(canary));assert.ok(!JSON.stringify(c.trace('redacted-status')).includes(canary));assert.equal(result.production.jev.primary.responseModel,undefined);assert.ok(result.production.trace.eventCount>0);}finally{await c.dispose();}
});
