import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,symlink,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {readSnapshot,normalizeRun} from '../src/state.js';
const run={id:'test-run',goal:'Check workflow',status:'running',startedAt:'2026-10-09T10:00:00Z',stages:[{stage:'work',status:'running',summary:'Inspect source',evidence:['Read file']}],decision:{model:'fixture',effectiveRoute:'plan_review',confidence:.7,probabilities:{plan_review:.7},secret:'excluded'}};
test('normalizes only whitelisted producer state',()=>{const s=normalizeRun(run);assert.equal(s.stage,'work');assert.equal(s.jev.confidence,.7);assert.equal(s.jev.secret,undefined);assert.throws(()=>normalizeRun({}));});
test('validates status/confidence and limits text/evidence',()=>{const s=normalizeRun({...run,decision:{confidence:99},stages:[{stage:'plan',status:'unsafe',summary:'x'.repeat(3000),evidence:Array(40).fill('e')}]});assert.equal(s.jev.confidence,undefined);assert.equal(s.stages[0].status,'pending');assert.equal(s.stages[0].summary.length,2000);assert.equal(s.stages[0].evidence.length,20);});
test('explicit bounded regular-file input only',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'dsh-state-'));try{const file=path.join(dir,'run.json');await writeFile(file,JSON.stringify(run));assert.equal((await readSnapshot(file)).title,'Check workflow');await assert.rejects(readSnapshot('relative.json'));await symlink(file,path.join(dir,'link.json'));await assert.rejects(readSnapshot(path.join(dir,'link.json')));await writeFile(file,' '.repeat(1024*1024+1));await assert.rejects(readSnapshot(file));}finally{await rm(dir,{recursive:true,force:true});}});
test('unconfigured remains waiting',async()=>assert.equal((await readSnapshot()).mode,'waiting'));
test('latest event timestamp survives out-of-order stage updates; mode and run preserved',()=>{const s=normalizeRun({...run,mode:'inspect',stages:[{stage:'review',status:'completed',time:'2026-10-09T10:00:00Z'},{stage:'work',status:'running',time:'2026-10-09T11:00:00Z'}]});assert.equal(s.updatedAt,'2026-10-09T11:00:00Z');assert.equal(s.executionMode,'inspect');assert.equal(s.runId,'test-run');});
test('strips control and bidi instructions from displayed evidence',()=>{const s=normalizeRun({...run,goal:'safe\u202Eevil\u0000',stages:[{stage:'work',summary:'ok\u2066spoof',evidence:['a\u001bb']}]});assert.equal(s.title,'safeevil');assert.equal(s.stages[0].summary,'okspoof');assert.equal(s.stages[0].evidence[0],'ab');});
test('failed routing remains a failed routing phase, without exposing producer error',()=>{const s=normalizeRun({...run,decision:null,routing:'failed',status:'blocked',stages:[],error:'secret credential'});assert.equal(s.routingStatus,'failed');assert.equal(s.stage,'jev-routing');assert.equal(s.error,undefined);});
