import {test}from'node:test';import assert from'node:assert/strict';import{createTeamRuntime}from'../src/team-runtime.js';import{teamHost,settings,waitFor}from'./helpers/team-host.mjs';
const input=(runtime,id='fixture-session',requestId='fixture-request')=>({sessionId:id,contextKey:runtime.snapshot(id).context.contextKey,requestId,goal:'Only test synthetic data',settings:settings()});
test('explicit start binds session and stable request identity; mounting never executes',async()=>{const f=teamHost({hold:true});const r=createTeamRuntime(f.ctx);try{assert.equal(f.calls.length,0);const req=input(r);const[first,again]=await Promise.all([r.start(req),r.start(req)]);assert.equal(first.snapshot.id,again.snapshot.id);await waitFor(()=>f.calls.length);assert.equal(f.calls.length,1);assert.equal(r.snapshot('missing').context.canStart,false);r.cancel({sessionId:'fixture-session',runId:first.snapshot.id});await waitFor(()=>r.snapshot('fixture-session').snapshot.status==='cancelled');}finally{await r.dispose();}});
test('process-wide team lease blocks other sessions before any provider starts',async()=>{const f=teamHost({hold:true}),g=teamHost({sessionId:'session-b'});const a=createTeamRuntime(f.ctx),b=createTeamRuntime(g.ctx);try{const first=await a.start(input(a));await assert.rejects(b.start(input(b,'session-b','other-request')),/已有团队/);assert.equal(g.calls.length,0);assert.equal(b.snapshot('session-b').context.canStart,false);a.cancel({sessionId:'fixture-session',runId:first.snapshot.id});await waitFor(()=>a.snapshot('fixture-session').snapshot.status==='cancelled');}finally{await a.dispose();await b.dispose();}});
test('context key rejects widened permissions before explicit start',async()=>{const f=teamHost();const r=createTeamRuntime(f.ctx);try{const stale=input(r);await f.setMode('danger-full-access');await assert.rejects(r.start(stale),/会话已变化/);assert.equal(f.calls.length,0);assert.notEqual(r.snapshot('fixture-session').context.contextKey,stale.contextKey);}finally{await r.dispose();}});
test('permission change during a run cancels children, retains parent mutation guard until cleanup',async()=>{const f=teamHost({hold:true});const r=createTeamRuntime(f.ctx);try{const result=await r.start(input(r));await waitFor(()=>f.calls.length);assert.ok(f.parentGuards.length);assert.ok(f.parentGuards[0]({agent:f.parent,name:'write'}));await f.setMode('read-only');await waitFor(()=>r.snapshot('fixture-session').snapshot.status==='cancelled');await waitFor(()=>!f.parentGuards.length);assert.equal(f.calls[0].signal.aborted,true);}finally{await r.dispose();}});
test('metadata preflight reserves global lease without inference',async()=>{const f=teamHost({preflightHold:true}),g=teamHost({sessionId:'b'});const a=createTeamRuntime(f.ctx),b=createTeamRuntime(g.ctx);try{const promise=a.start(input(a));await new Promise(r=>setTimeout(r,10));await assert.rejects(b.start(input(b,'b','request-b')),/已有团队/);assert.equal(f.calls.length,0);f.releasePreflight();await promise;await waitFor(()=>['completed','blocked','failed'].includes(a.snapshot('fixture-session').snapshot.status));}finally{await a.dispose();await b.dispose();}});
test('cleanup failure poisons the process lease across runtime replacement and never claims stopped',async()=>{const f=teamHost({cleanupFail:true});const a=createTeamRuntime(f.ctx);try{await a.start(input(a));await waitFor(()=>a.snapshot('fixture-session').snapshot.status==='blocked');assert.match(a.snapshot('fixture-session').snapshot.message,/不能宣称已停止/);await a.dispose();const g=teamHost({sessionId:'replacement'}),b=createTeamRuntime(g.ctx);try{await assert.rejects(b.start(input(b,'replacement','new-request')),/清理未确认/);assert.equal(g.calls.length,0);}finally{await b.dispose();}}finally{await a.dispose();/* Test-only process fixture reset, deliberately not exposed by production. */globalThis[Symbol.for('dsh-desktop-workflow:exclusive-run:v2')].current=null;}});
test('a failed worker cleanup cancels the current run before any independent next worker starts',async()=>{const tasks=['one','two'].map(id=>({id,role:'worker',title:id,instructions:'Synthetic write task',dependsOn:[]}));const f=teamHost({tasks,cleanupFail:role=>role==='worker'});const a=createTeamRuntime(f.ctx);try{await a.start(input(a));await waitFor(()=>a.snapshot('fixture-session').snapshot.message?.includes('清理未确认'));await new Promise(r=>setTimeout(r,20));assert.equal(f.calls.filter(x=>x.label.includes(' worker ')).length,1);assert.equal(a.snapshot('fixture-session').context.canStart,false);}finally{await a.dispose();globalThis[Symbol.for('dsh-desktop-workflow:exclusive-run:v2')].current=null;}});
