import{test}from'node:test';import assert from'node:assert/strict';import{createVerifier,safeRelative,verificationProfiles}from'../src/verification.js';
const profile={id:'fixture',name:'Explicit fixture',checks:[{id:'test',argv:['node','--test','test.mjs'],timeoutMs:1000}],protectedPaths:['test.mjs']};
const config={sessionId:'s',verification:{profileId:'fixture',scope:['src']}};const signal=new AbortController().signal;
function setup(value){const calls=[],poisons=[];return {calls,poisons,v:createVerifier({profiles:[profile],executeTool:async(s,spec)=>{calls.push({s,...spec});return typeof value==='function'?value(spec):value;},poison:s=>poisons.push(s)})};}
test('scope and fixed server profiles reject traversal, executable payloads and missing check protection',()=>{for(const s of ['../src','/root','src/../other','src\\x','src/**','.', 'a//b'])assert.equal(safeRelative(s),false);assert.ok(safeRelative('src/file.js'));assert.throws(()=>verificationProfiles([{...profile,checks:[]} ]));assert.throws(()=>verificationProfiles([{...profile,protectedPaths:[]} ]));assert.throws(()=>verificationProfiles([{...profile,checks:[{id:'bad',argv:['node','\0'],timeoutMs:1000}]}]));const {v}=setup({});assert.throws(()=>v.preflight({verification:{profileId:'unknown',scope:['src']}}));});
test('trusted checker calls native bash with original session and fixed foreground args only',async()=>{const {v,calls}=setup({isError:false,value:{kind:'foreground',exitCode:0,stdout:{text:'{}',truncated:false},stderr:{text:'',truncated:false}}});await assert.rejects(v.collect({config,runId:'run',round:0,phase:'baseline',signal}),/验证未通过/);assert.equal(calls[0].s,'s');assert.equal(calls[0].name,'bash');assert.equal(calls[0].arguments.run_in_background,false);assert.ok(!('sandbox_permissions'in calls[0].arguments));assert.ok(!('justification'in calls[0].arguments));assert.match(calls[0].arguments.command,/hostVerifier/);});
test('background promotion, timeout, aborted result and unknown dispatch all poison lease',async()=>{for(const result of [{isError:true},{},{isError:false,value:{kind:'promoted',jobId:'j'}},{isError:false,value:{kind:'background',jobId:'j'}},{isError:false,value:{kind:'foreground',timedOut:true}},{isError:false,value:{kind:'foreground',aborted:true}}]){const {v,poisons}=setup(result);await assert.rejects(v.collect({config,runId:'run',round:0,phase:'baseline',signal}));assert.deepEqual(poisons,['s']);}});
test('foreign run/round/nonce, malformed output and truncated logs never become evidence',async()=>{for(const text of ['{}','{"clean":true,"runId":"wrong","round":0}', 'not JSON']){const {v}=setup({isError:false,value:{kind:'foreground',exitCode:0,stdout:{text,truncated:false},stderr:{text:'',truncated:false}}});await assert.rejects(v.collect({config,runId:'run',round:0,phase:'baseline',signal}));}const {v}=setup({isError:false,value:{kind:'foreground',exitCode:0,stdout:{text:'{}',truncated:true}}});await assert.rejects(v.collect({config,runId:'run',round:0,phase:'baseline',signal}));});
test('catalog exposes detached actual argv, timeouts and protected paths',()=>{const {v}=setup({});assert.deepEqual(v.profiles[0].checks,profile.checks);v.profiles[0].checks[0].argv.push('bad');assert.deepEqual(v.preflight(config).checks,profile.checks);});
