import React,{useState} from 'react';
import{createRoot}from'react-dom/client';
import{TeamView}from'../client/TeamView';
import{teamDemoSnapshot}from'../client/team-demo';
import{createDefaultTeamSettings,type TeamCatalog,type TeamSnapshot}from'../client/team-types';
const roles=['planner','coordinator','researcher','explorer','worker','reviewer']as const;
const names={planner:'模拟·规划模型',coordinator:'模拟·主力模型',researcher:'模拟·轻量模型',explorer:'模拟·轻量模型',worker:'模拟·主力模型',reviewer:'模拟·审查模型'};
const catalog:TeamCatalog={available:true,jev:{configured:true,available:true,mode:'fixture',endpoint:'fixture://typesafe/jev（仅作离线界面演示）',disclosure:'【离线 Fixture】真实运行会向 TypeSafe 的 Jev 服务发送任务目标、上下文摘要、计划、公开产出、差异与验证结果，用于分类与下一步决策。本预览不发送任何数据。'},verificationProfiles:[{id:'fixture-test-build',name:'Fixture · 测试与构建检查',checks:[{id:'fixture-unit',argv:['npm','test'],timeoutMs:60000},{id:'fixture-build',argv:['npm','run','build'],timeoutMs:30000}],protectedPaths:['test','package.json'],expectsChanges:true}],providers:[{id:'preview-fixture',name:'仅供预览的模拟目录',models:[...new Set(Object.values(names))].map(id=>({id,name:id,efforts:[{id:'fixture-standard',name:'模拟标准'},{id:'fixture-deep',name:'模拟深入'}]}))}]};
function Preview(){
  const[mode,setMode]=useState('演示拓扑');const[dark,setDark]=useState(false);const[narrow,setNarrow]=useState(false);const[error,setError]=useState<string>();
  const[settings,setSettings]=useState(()=>{const x=createDefaultTeamSettings();for(const r of roles)x.roles[r]={provider:'preview-fixture',model:names[r],maxTokens:4096};x.verification={profileId:'fixture-test-build',scope:['src','test']};return x;});
  let snapshot:TeamSnapshot|null=['演示拓扑','完成','受阻'].includes(mode)?teamDemoSnapshot():null;
  if(snapshot)snapshot={...snapshot,roles:settings.roles};
  if(mode==='完成'&&snapshot)snapshot={...snapshot,status:'completed',finishedAt:'2026-10-09T09:45:00.000Z',message:'【Fixture】全部检查通过的合成完成状态。未运行真实检查。',jev:{...snapshot.jev!,evidence:{checksPassed:true,scopeOk:true,diffAvailable:true,verified:true,reason:'【Fixture】测试、修改范围、差异与独立验证全部通过，仅为合成证据。'}},nodes:snapshot.nodes.map(n=>({...n,status:'completed'}))};
  if(mode==='受阻'&&snapshot)snapshot={...snapshot,status:'blocked',message:'【Fixture】修改越出允许路径，完成门禁阻止交付。',jev:{...snapshot.jev!,lane:'escalate',round:2,decisions:[...snapshot.jev!.decisions,{phase:'step',action:'escalate',lane:'escalate',round:2,confidence:.98,reason:'【Fixture】范围检查不通过，需要人工处理。'}],evidence:{checksPassed:true,scopeOk:false,diffAvailable:true,verified:false,reason:'【Fixture】检测到允许的 src、test 之外存在变更；即使测试通过也不能完成。'}}};
  const shownCatalog=mode==='缺少凭据'?{...catalog,jev:{...catalog.jev!,configured:false,available:false,mode:'live' as const,reason:'Jev 服务端凭据未配置。浏览器不能输入或保存密钥。'}}:mode==='无验证配置'?{...catalog,verificationProfiles:[]}:catalog;
  return <><div style={{font:'12px system-ui',padding:'10px 18px',display:'flex',alignItems:'center',gap:12,flexWrap:'wrap',background:dark?'#1b202b':'#fff',color:dark?'#eef1f8':'#475467',borderBottom:'1px solid #dbe1e9'}}><strong>v0.3 Jev 离线组件预览</strong><span>Fixture 合成目录、决策与证据 · 不连接宿主 / TypeSafe · 不调用模型</span><select aria-label="预览状态" value={mode} onChange={e=>{setMode(e.target.value);setError(undefined);}}>{['演示拓扑','配置交互','完成','受阻','缺少凭据','无验证配置'].map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>{document.body.toggleAttribute('data-ds-dark-theme',!dark);setDark(!dark);}}>主题：{dark?'深色':'浅色'}</button><button onClick={()=>setNarrow(!narrow)}>{narrow?'展开画布':'侧栏宽度'}</button></div><div style={{maxWidth:narrow?420:1500,margin:'24px auto',minHeight:700}}><TeamView catalog={shownCatalog} sessionId="preview-session" sessionContext={{contextKey:'fixture-context',canStart:true,workspace:'/仅为示例/项目目录',permissionNotice:'离线预览，不产生模型调用。真实运行继承当前宿主权限；额外审批请求会被拒绝。'}} snapshot={snapshot} settings={settings} error={error} onSettingsChange={setSettings} onStart={()=>setError('Fixture 确认交互已完成：本预览未启动任务、未调用模型，也未向 TypeSafe 发送数据。')} onCancel={()=>setError('Fixture 没有真实运行，无需取消。')} onRefresh={()=>{setMode('配置交互');setError(undefined);}} onDemo={()=>setMode(mode==='演示拓扑'?'配置交互':'演示拓扑')}/></div></>;
}
createRoot(document.getElementById('root')!).render(<Preview/>);
