import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { TeamView, TeamSettingsView } from '../client/TeamView';
import { teamDemoSnapshot } from '../client/team-demo';
import { createDefaultTeamSettings, type TeamCatalog, type TeamSnapshot } from '../client/team-types';
const roles = ['planner', 'coordinator', 'researcher', 'explorer', 'worker', 'reviewer'] as const;
const names = { planner: '模拟·规划模型', coordinator: '模拟·主力模型', researcher: '模拟·轻量模型', explorer: '模拟·轻量模型', worker: '模拟·主力模型', reviewer: '模拟·审查模型' };
const catalog: TeamCatalog = { available: true, jev: { configured: true, available: true, mode: 'fixture', endpoint: 'fixture://typesafe/jev（离线演示）', disclosure: '本预览不向任何服务发送数据。' }, providers: [{ id: 'preview-fixture', name: '仅供预览的模拟目录', models: [...new Set(Object.values(names))].map(id => ({ id, name: id, efforts: [{ id: 'fixture-standard', name: '模拟标准' }, { id: 'fixture-deep', name: '模拟深入' }] })) }] };
function Preview() {
  const [mode, setMode] = useState('演示拓扑'); const [dark, setDark] = useState(true); const [narrow, setNarrow] = useState(false); const [notice, setNotice] = useState<string>();
  const [setup, setSetup] = useState(() => { const settings = createDefaultTeamSettings(); for (const role of roles) settings.roles[role] = { provider: 'preview-fixture', model: names[role], maxTokens: 4096 }; return { settings, configured: true, keyConfigured: true, disclosureAccepted: true, revision: 1 }; });
  let snapshot: TeamSnapshot | null = ['演示拓扑', '完成', '待验证', '受阻'].includes(mode) ? teamDemoSnapshot() : null;
  if (snapshot) snapshot = { ...snapshot, roles: setup.settings.roles };
  if (mode === '完成' && snapshot) snapshot = { ...snapshot, status: 'completed', finishedAt: '2026-10-09T09:45:00.000Z', message: '【Fixture】全部检查通过的合成完成状态。未运行真实检查。', jev: { ...snapshot.jev!, evidence: { checksPassed: true, scopeOk: true, diffAvailable: true, verified: true, reason: '【Fixture】所有门禁通过，仅为合成证据。' } }, nodes: snapshot.nodes.map(node => ({ ...node, status: 'completed' })) };
  if (mode === '待验证' && snapshot) snapshot = { ...snapshot, status: 'unverified', message: '【Fixture】已产生允许范围内的项目改动，但未识别到可自动运行的验收命令，结果待验证。', jev: { ...snapshot.jev!, lane: 'escalate', evidence: { checksPassed: false, scopeOk: true, diffAvailable: true, verified: false, reason: '【Fixture】缺少适用验证命令；已保留允许范围内的改动，结果待验证，不宣称验证通过。' } } };
  if (mode === '受阻' && snapshot) snapshot = { ...snapshot, status: 'blocked', message: '【Fixture】修改范围检查失败，运行被阻止，请检查项目差异。', jev: { ...snapshot.jev!, evidence: { checksPassed: true, scopeOk: false, diffAvailable: true, verified: false, reason: '【Fixture】范围检查失败，不能交付已验证的结果。' } } };
  if (snapshot && ['完成', '待验证', '受阻'].includes(mode)) {
    const finishedAt = '2026-10-09T09:45:00.000Z';
    snapshot = { ...snapshot, finishedAt, nodes: snapshot.nodes.map(node => ({ ...node, status: node.status === 'running' || node.status === 'pending' ? (mode === '受阻' ? 'blocked' : 'completed') : node.status, ...(node.status === 'running' || node.status === 'pending' ? { finishedAt, output: `【Fixture】${mode === '受阻' ? '运行已阻止，保留已报告证据。' : '本次执行已结束，最终状态由完成检查决定。'}` } : {}) })), jev: { ...snapshot.jev!, decisions: [...snapshot.jev!.decisions, { phase: 'step', action: mode === '完成' ? 'finish' : 'escalate', lane: snapshot.jev!.lane, round: snapshot.jev!.round, confidence: 1, reason: `【Fixture】${mode === '完成' ? '所有合成完成证据通过。' : mode === '待验证' ? '未找到适用检查，保留改动并标为待验证。' : '范围检查失败，本次运行被阻止。'}` }] } };
  }
  return <><div style={{ font: '12px system-ui', padding: '10px 18px', display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap', background: dark ? '#1b202b' : '#fff', color: dark ? '#eef1f8' : '#475467', borderBottom: '1px solid #dbe1e9' }}><strong>v0.4 /team 离线预览</strong><span>Fixture 合成数据 · 不连接宿主 / TypeSafe · 请勿输入真实密钥</span><select aria-label="预览状态" value={mode} onChange={event => { setMode(event.target.value); setNotice(undefined); }}>{['演示拓扑', '待命', '一次性设置', '完成', '待验证', '受阻'].map(value => <option key={value}>{value}</option>)}</select><button onClick={() => { document.body.toggleAttribute('data-ds-dark-theme', !dark); setDark(!dark); }}>主题：{dark ? '深色' : '浅色'}</button><button onClick={() => setNarrow(!narrow)}>{narrow ? '展开画布' : '侧栏宽度'}</button></div><div style={{ maxWidth: narrow ? 420 : 1500, margin: '16px auto', minHeight: 700 }}>{mode === '一次性设置' ? <TeamSettingsView setup={setup} catalog={catalog} credential={{ configured: true, writable: true, source: 'fixture' }} notice={notice} onClose={() => setMode('待命')} onRefresh={() => setNotice('Fixture 预览，未连接或读取真实凭据。')} onSave={async input => { setSetup({ settings: input.settings, configured: input.disclosureAccepted && Object.values(input.settings.roles).every(role => !!role.provider && !!role.model), keyConfigured: true, disclosureAccepted: input.disclosureAccepted, revision: setup.revision + 1 }); setNotice('Fixture 设置交互完成，未保存密钥、未发出网络请求。'); }}/> : <TeamView catalog={catalog} sessionId="preview-session" sessionContext={{ workspace: '/仅为示例/项目目录', permissionNotice: '离线预览，不产生模型调用。' }} snapshot={snapshot} settings={setup.settings} configured={setup.configured} onOpenSettings={() => setMode('一次性设置')} onCancel={async () => {}} onRefresh={() => setMode('待命')} onDemo={() => setMode(mode === '演示拓扑' ? '待命' : '演示拓扑')}/>}</div></>;
}
createRoot(document.getElementById('root')!).render(<Preview/>);
