export function teamHost({sessionId='fixture-session',hold=false,cleanupFail=false,preflightHold=false,tasks}={}){
 const listeners=new Map();let mode='workspace-write';const calls=[];let releasePreflight;
 const on=(name,fn)=>{const list=listeners.get(name)||[];list.push(fn);listeners.set(name,list);return()=>list.splice(list.indexOf(fn),1);};
 const parentGuards=[];
 const parent={id:sessionId,status:'idle',session:{id:sessionId,header:{cwd:'/fixture/shared-project'}},ctx:{get:()=>({guard(fn){parentGuards.push(fn);return()=>parentGuards.splice(parentGuards.indexOf(fn),1);}})}};
 const ctx={on,get:name=>name==='sandboxPolicy'?{resolve:()=>({mode,workspaceRoot:'/fixture/shared-project'})}:undefined,agents:{get:id=>id===parent.id?parent:undefined,isOwnedBy:(_id,p)=>p===parent},llm:{listProviders:()=>[{id:'fixture',name:'Test-only provider'}],listModels:async()=>[{id:'model',name:'Test-only model'}],resolveModelInfo:async()=>({}),resolveCallConfig:async x=>{if(preflightHold)await new Promise(r=>{releasePreflight=r;});return x;}},subagents:{getProvider:()=>({capabilities:{agentOptions:true,outputSchema:true,persona:true,depthLimit:true}}),resolveMaxDepth:()=>1,async start(provider,request){calls.push(request);const role=request.label.split(' ')[1];const childEvents=new Map();const agent={id:'fixture-child-'+calls.length,session:{header:{parentSession:parent.id}},ctx:{get:()=>({guard:()=>()=>{},presentAs:()=>()=>{}}),on(name,fn){childEvents.set(name,fn);return()=>{};}}};for(const fn of listeners.get('agent/created')||[])await fn({agent});
 const plan={summary:'Deterministic plan',tasks:tasks||[{id:'read',role:'explorer',title:'Read fixture',instructions:'Read only the synthetic fixture',dependsOn:[]}]};const structured=role==='reviewer'?{verdict:'approve',summary:'Fixture approved',issues:[]}:role==='router'?{route:'plan',summary:'Fixture route'}:plan;
 const result=hold?new Promise(resolve=>{request.signal.addEventListener('abort',()=>resolve({stopReason:'aborted',output:[]}),{once:true});}):Promise.resolve({stopReason:'completed',structured,output:[{type:'text',text:'Synthetic result only'}]});
 return {id:agent.id,localAgent:agent,result,async dispose(){if(typeof cleanupFail==='function'?cleanupFail(role):cleanupFail)throw Error('fixture cleanup failure');for(const fn of listeners.get('agent/disposed')||[])fn({agent});}};
 }}};
 const emit=async(name,...args)=>{for(const fn of listeners.get(name)||[])await fn(...args);};
 return {ctx,parent,calls,parentGuards,releasePreflight:()=>{preflightHold=false;releasePreflight?.();},async setMode(next){mode=next;await emit('session/event',parent.session,{type:'sandbox/mode'});},emit};
}
export const settings=()=>({roles:Object.fromEntries(['planner','coordinator','researcher','explorer','worker','reviewer'].map(role=>[role,{provider:'fixture',model:'model',maxTokens:4096}])),limits:{concurrency:2,maxAgents:12,maxTasks:8,maxRetries:0,maxDurationMs:30000,maxStepsPerAgent:8},reviewPlan:true,routeEnabled:false});
export const waitFor=async(test)=>{for(let i=0;i<200;i++){const value=test();if(value)return value;await new Promise(r=>setTimeout(r,5));}throw Error('Fixture condition timed out');};
